
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]			
name = "QupyRibbon"
version = "0.2.0"
authors = [
	{name="Corey Hooge", email="hyperion.geo@gmail.com"},	
]
description = 'Ribbon grabbed from internet but reorged and improved'
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
classifiers = [
		"Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ]
dependencies = [ 
]

[project.urls]
"Homepage" = 'https://github.com/hyperiongeo/qupyribbon'
"Bug Tracker" = "https://github.com/hyperiongeo/qupyribbon/issues"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools]
include-package-data = true
